// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"fmt"
	"github.com/go-playground/validator/v10"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/sonofsun61/APIFromSpec/internal/authclient"
	"github.com/sonofsun61/APIFromSpec/internal/config"
	"github.com/sonofsun61/APIFromSpec/internal/database"
	"github.com/sonofsun61/APIFromSpec/internal/handler"
	"github.com/sonofsun61/APIFromSpec/internal/repository/postgres"
	"github.com/sonofsun61/APIFromSpec/internal/service"
	"google.golang.org/grpc"
	"net/http"
)

// Injectors from wire.go:

func InitializeApp() *App {
	configConfig := config.MustLoadConfig()
	context := ProvideContext()
	connString := ProvideConnString(configConfig)
	pool := database.MustConnectToDatabase(context, connString)
	postgresClientRepository := postgres.NewPostgresClientRepository(pool)
	clientService := service.NewClientService(postgresClientRepository)
	v := ProvideValidatorOptions()
	validate := validator.New(v...)
	clientHandler := handler.NewClientHandler(clientService, validate)
	postgresSupplierRepository := postgres.NewPostgresSupplierRepository(pool)
	supplierService := service.NewSupplierService(postgresSupplierRepository)
	supplierHandler := handler.NewSupplierHandler(supplierService, validate)
	postgresProductRepository := postgres.NewPostgresProductRepository(pool)
	productService := service.NewProductService(postgresProductRepository)
	productHandler := handler.NewProductHandler(productService, validate)
	postgresImageRepository := postgres.NewPostgresImageRepository(pool)
	imageService := service.NewImageService(postgresImageRepository)
	imageHandler := handler.NewImageHandler(imageService, validate)
	clientConn := ProvideAuthConn(configConfig)
	client := authclient.New(clientConn)
	authHandler := handler.NewAuthHandler(client, validate)
	httpHandler := handler.SetUpRouter(clientHandler, supplierHandler, productHandler, imageHandler, authHandler, client)
	app := ProvideApp(configConfig, pool, httpHandler)
	return app
}

// wire.go:

func ProvideApp(config2 *config.Config, pool *pgxpool.Pool, router http.Handler) *App {
	return &App{
		config: config2,
		pool:   pool,
		router: router,
	}
}

func ProvideContext() context.Context {
	return context.Background()
}

func ProvideValidatorOptions() []validator.Option {
	return nil
}

func ProvideConnString(cfg *config.Config) database.ConnString {
	return database.ConnString(cfg.ConnString)
}

func ProvideAuthConn(cfg *config.Config) *grpc.ClientConn {
	grpcClientConn, err := authclient.NewConn(cfg.AuthServiceAddr)
	if err != nil {
		panic(fmt.Sprintf("could not create auth service connection: %v", err))
	}
	return grpcClientConn
}
